name: terraform-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: check
        run: |
         terraform init  
         terraform validate
         terraform fmt -recursive
      - name: plan
        run: terraform plan
      
       

      