name: terraform-build

on:
  push:
    branches:
      - main
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY}}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: check
        run: |
         terraform init  
         terraform validate
         terraform fmt -recursive
      - name: plan
        run: terraform plan
      - name: apply
        run: terraform apply -auto-approve
      
       

      