name: terraform-build

on:
  push:
    branches:
      - main

#  pull_request:
 #   branches:
 #     - stage
  
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY}}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: check
        run: |
         terraform init  
         terraform validate

      - name: check
        run: terraform fmt -check

      - name: plan
        run: terraform plan
        #if: success()
        #if: github.event_name == 'pull_request'

      - name: apply
        run: terraform apply -auto-approve
       # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      
       

      